### PR TITLE
Translate for English language.

### PR DESCRIPTION
**Pull request by M-Razavi**
Add English translation for labels and messages.

### CODE REVIEW

**Review by M-Razavi — COMMENTED** [review]
Double check

**Comment by hsluoyz** [comment]
lgtm

**Comment by hsluoyz** [comment]
@M-Razavi , I forgot to see that this PR is merged into `English_version`, can you make a PR to merge into master?

**Comment by M-Razavi** [comment]
@hsluoyz I can create a new PR to merge it into the master if like

**Comment by hsluoyz** [comment]
@M-Razavi yes, please :)

**Pull request merged**
