### PR TITLE
English version

### PR DESCRIPTION
**Pull request by M-Razavi**
Translate to English

### CODE REVIEW

**Comment by hsluoyz** [comment]
Hi @M-Razavi , very appreciated this work. In fact, we have actually a English-version branch here: https://github.com/casbin/web-ui/tree/English_version. That branch is translated by myself.

What's the relationship between this PR and that branch? Is this based on that previous work? I mean we should merge these works together to get the best translation. BTW, how did you translate these Chinese words into English? I found it's very accurate :)

**Comment by M-Razavi** [comment]
I tried to find an English version but just found an incomplete version so I used an online translator to translate the current version. Merging these two might leads to a better version.

**Comment by hsluoyz** [comment]
Need rework?

**Comment by M-Razavi** [comment]
Is it possible to mix them?

**Comment by hsluoyz** [comment]
Yes. Can you re-organize your commits in this PR? I even saw 3 my own commits show up here. Maybe your PR can contain only one commit.

**Comment by M-Razavi** [comment]
I reorganize commits in a new pull request. https://github.com/casbin/web-ui/pull/4

**Pull request closed without merging**
